name: hello-world
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - manual-hello-world
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"